/* Conteúdo da trilha. Para adicionar um tópico, basta incluir um objeto em `topics`.
   Campos: name, kw (palavras-chave), what, why, how[] (passos), tools[], projects{ini,mid,sen}, q, a */
const MODULES = [
{ id:"comp", name:"Teoria geral da computação", color:"#38bdf8",
  tip:"Todo software, do mais simples ao mais complexo, é entrada, processamento e saída. Domine isso e o resto fica leve.",
  topics:[
  { name:"IN / PROC / OUT", kw:"Entrada, Processamento, Saída, Condicionais, Laços, Subprogramas, Intenção, Ato, Agente",
    what:"Modelo que descreve qualquer programa: recebe dados, transforma e devolve um resultado.",
    why:"Evita começar a codar sem saber o que entra e o que deve sair.",
    how:["Antes de codar, monte uma tabela Entrada | Processamento | Saída.","Liste as condições (se/senão) e repetições do processamento.","Transforme cada bloco em uma função."],
    tools:["Papel","draw.io","Python","VS Code"],
    projects:{ini:"Calculadora de IMC",mid:"Conversor de moedas consumindo API",sen:"Motor de regras para cálculo de frete com testes"},
    q:"O que define a fronteira de um programa no modelo IN/PROC/OUT?", a:"O que ele recebe (entrada) e o que entrega (saída). O processamento é o meio entre os dois." },
  { name:"Programação e lógica", kw:"Monolítico, Iterativo, Recursivo, Descrição narrativa, Fluxograma, Pseudocódigo",
    what:"Formas de descrever e estruturar a solução de um problema antes e durante a codificação.",
    why:"Quem domina lógica troca de linguagem sem sofrer.",
    how:["Escreva a solução em pseudocódigo.","Desenhe o fluxograma das decisões.","Implemente primeiro iterativo e depois tente a versão recursiva."],
    tools:["Portugol Studio","Mermaid","Python","JavaScript"],
    projects:{ini:"Jogo de adivinhação de número",mid:"Gerenciador de tarefas em linha de comando",sen:"Interpretador de expressões matemáticas"},
    q:"Quando a recursão é preferível à iteração?", a:"Quando o problema se divide em subproblemas iguais, como árvores e Torre de Hanoi." },
  { name:"Hardware", kw:"CPU, Memória, RAM, ROM, Placa-mãe",
    what:"Componentes físicos que executam e armazenam os programas.",
    why:"Explica desempenho, gargalos e limites de memória do seu código.",
    how:["Monte um diagrama de como CPU, RAM e disco se comunicam.","Meça o uso de memória de um programa seu.","Compare dois computadores para uma mesma tarefa."],
    tools:["Gerenciador de tarefas","htop","CPU-Z","Wokwi"],
    projects:{ini:"Guia comparativo de peças para um PC",mid:"Simulador do ciclo busca-decodifica-executa",sen:"Emulador CHIP-8 em JavaScript"},
    q:"Qual a diferença prática entre RAM e ROM?", a:"RAM é volátil e guarda dados em uso. ROM é permanente e guarda instruções básicas." },
  { name:"Pensamento computacional", kw:"Controle de fluxos, Decomposição, Padrões, Abstração, Algoritmo, Von Neumann",
    what:"Quatro habilidades: decompor, reconhecer padrões, abstrair e criar algoritmos.",
    why:"É o método mental para resolver problemas novos de qualquer área.",
    how:["Quebre o problema em partes pequenas.","Procure o que se repete.","Ignore detalhes irrelevantes e escreva os passos."],
    tools:["Scratch","Code.org","Excalidraw","LeetCode"],
    projects:{ini:"Roteiro passo a passo de uma receita ou rotina",mid:"Resolver Torre de Hanoi e Sudoku",sen:"Modelagem abstrata de um sistema de biblioteca com diagrama UML"},
    q:"O que é abstração?", a:"Esconder detalhes que não importam agora para focar no que resolve o problema." }
]},
{ id:"eng", name:"Engenharia de Software", color:"#a78bfa",
  tip:"Engenharia é o que separa um código que funciona hoje de um produto que sobrevive por anos.",
  topics:[
  { name:"Mapa SWEBOK", kw:"Requisitos, Design, Construção, Teste, Manutenção, Configuração, Gestão, Processos, Qualidade",
    what:"Guia que organiza as áreas de conhecimento da profissão.",
    why:"Mostra o ciclo completo e onde você ainda tem lacunas.",
    how:["Crie um checklist com as áreas do SWEBOK.","Marque o que seu projeto já cobre.","Preencha uma lacuna por semana."],
    tools:["Notion","GitHub Projects","Markdown"],
    projects:{ini:"Checklist SWEBOK do seu projeto atual",mid:"Documentar um projeto passando por todas as áreas",sen:"Auditoria de qualidade de um repositório open source"},
    q:"Cite cinco áreas do SWEBOK.", a:"Requisitos, design, construção, teste e manutenção, entre outras." },
  { name:"Manifesto Ágil", kw:"Código, Manuais operacionais, Metodologias aplicáveis, Documentação contínua, Definição, Desenvolvimento, Operação",
    what:"Quatro valores e doze princípios que priorizam pessoas, software funcionando, colaboração e adaptação.",
    why:"É a base de Scrum, XP, Kanban e do DevOps moderno.",
    how:["Entregue em pequenos incrementos.","Faça uma retrospectiva ao fim de cada ciclo.","Mantenha documentação enxuta e viva."],
    tools:["Trello","GitHub Projects","Miro"],
    projects:{ini:"Kanban pessoal de estudos",mid:"Retrospectiva de um projeto passado com plano de ação",sen:"Entregas incrementais com release notes automáticas"},
    q:"O Manifesto Ágil elimina a documentação?", a:"Não. Valoriza software funcionando mais que documentação abrangente." },
  { name:"Scrum e Extreme Programming", kw:"Product backlog/Owner, Sprint backlog, Sprint, TDD, Refatoração, Código vivo, Foco humano, Times",
    what:"Scrum organiza o time em sprints. XP traz práticas técnicas como TDD e refatoração.",
    why:"Une gestão de entrega com qualidade de código.",
    how:["Monte o product backlog e priorize.","Planeje uma sprint de uma semana.","Escreva o teste antes do código (vermelho, verde, refatorar)."],
    tools:["Jira","Jest","pytest","GitHub Issues"],
    projects:{ini:"App de tarefas desenvolvido em uma sprint",mid:"Kata TDD: FizzBuzz e Boliche",sen:"Squad simulada com PRs, pair programming e Definição de Pronto"},
    q:"Qual o ciclo do TDD?", a:"Escrever teste que falha, fazer passar, refatorar." },
  { name:"CMMI e MPS.BR", kw:"7 princípios de fundação, Modelo iterativo/incremental, Escalas de maturidade, Kitchenham",
    what:"Modelos que medem e melhoram a maturidade dos processos de software.",
    why:"Empresas e órgãos públicos exigem processos comprovados.",
    how:["Descreva seu processo atual.","Compare com os níveis do modelo.","Defina métricas e metas de melhoria."],
    tools:["Planilhas","Google Looker Studio","DORA metrics"],
    projects:{ini:"Template de processo para trabalhos de faculdade",mid:"Avaliar o processo de uma equipe por nível de maturidade",sen:"Plano de melhoria com indicadores DORA"},
    q:"O que mede um nível de maturidade?", a:"O quanto os processos são definidos, repetíveis e melhorados continuamente." }
]},
{ id:"ux", name:"Experiência do Usuário (UX)", color:"#f472b6",
  tip:"Software que ninguém entende é software que ninguém usa. Teste com gente real, sempre.",
  topics:[
  { name:"Nielsen, Norman e Bastien", kw:"Interação HC, Motor ágil, ISO 9241, Ergonomia, Affordance, 10 Heurísticas, Coleta triangulada, Sprints",
    what:"Autores e critérios clássicos para avaliar usabilidade, incluindo as 10 heurísticas de Nielsen.",
    why:"Permitem achar falhas de interface sem esperar o usuário reclamar.",
    how:["Percorra o app tela a tela com as 10 heurísticas.","Registre cada problema com nota de severidade.","Priorize e proponha correções."],
    tools:["Figma","Lookback","Maze","Planilha de severidade"],
    projects:{ini:"Avaliação heurística de um app de banco",mid:"Relatório com severidade e recomendações",sen:"Auditoria de usabilidade com coleta triangulada"},
    q:"Cite três heurísticas de Nielsen.", a:"Visibilidade do status, controle e liberdade do usuário, prevenção de erros." },
  { name:"Eficácia e satisfação", kw:"Mecânica, emoção, Ciclo de Eason/Shneidermam, Modelo em estrela, Resolução 196/96, Comunicabilidade",
    what:"Medidas de qualidade de uso: conseguir concluir a tarefa e ficar satisfeito. Inclui ética em pesquisa com pessoas.",
    why:"Transformam opinião em dado e protegem os participantes.",
    how:["Defina tarefas e a taxa de sucesso esperada.","Aplique o questionário SUS ao final.","Use termo de consentimento nos testes."],
    tools:["Google Forms","SUS","Hotjar","Termo de consentimento"],
    projects:{ini:"Questionário de satisfação de um site conhecido",mid:"Teste de eficácia com 5 usuários",sen:"Estudo comparativo de duas versões com análise estatística"},
    q:"Eficácia e satisfação são a mesma coisa?", a:"Não. Eficácia é concluir a tarefa. Satisfação é como o usuário se sentiu fazendo." },
  { name:"Canvas UX e ciclo UX", kw:"Ícones universais, Cores com cautela, Agrupamento semântico, Controle de localização, Framework Decide, UX Check",
    what:"Ferramentas para planejar a experiência: canvas, ciclo de vida e checklists de decisão.",
    why:"Alinham o time sobre quem é o usuário e qual problema resolver.",
    how:["Preencha o Canvas UX com persona e problema.","Mapeie a jornada do usuário.","Revise com um checklist UX Check."],
    tools:["Miro","FigJam","Whimsical"],
    projects:{ini:"Canvas UX de um app de estudos",mid:"Persona, jornada e mapa de empatia",sen:"Design sprint completo de 5 dias"},
    q:"Para que serve um Canvas UX?", a:"Para alinhar problema, usuário e solução em uma única página." },
  { name:"Cenários, protótipos e testes", kw:"Cenário de uso, Storyboarding, Wireframe, Mockup, Protótipo, Formativa, Somativa, MIS/MAC, Think-Aloud",
    what:"Sequência que vai da ideia ao protótipo testável, com avaliação formativa e somativa.",
    why:"Errar no papel custa minutos. Errar em produção custa semanas.",
    how:["Escreva o cenário de uso.","Faça wireframe e depois mockup.","Teste o protótipo com Think-Aloud."],
    tools:["Figma","Penpot","Balsamiq","Maze"],
    projects:{ini:"Wireframe de 3 telas",mid:"Protótipo clicável testado com 5 pessoas",sen:"Design system com testes formativos e somativos"},
    q:"Formativa ou somativa: qual acontece durante o design?", a:"A formativa, para corrigir o rumo. A somativa mede o resultado final." }
]},
{ id:"front", name:"Desenvolvimento Front End", color:"#34d399",
  tip:"O front-end é onde o usuário encontra o seu trabalho. Semântica e acessibilidade vêm antes do enfeite.",
  topics:[
  { name:"HTML semântico", kw:"Tags de conteúdo, Estrutura hierárquica do documento, Formulários, validação",
    what:"Usar a tag certa para cada conteúdo: header, nav, main, article, form.",
    why:"Melhora SEO, acessibilidade e manutenção.",
    how:["Troque divs genéricas por tags semânticas.","Mantenha uma hierarquia de títulos coerente.","Valide formulários com atributos nativos."],
    tools:["VS Code","W3C Validator","Lighthouse"],
    projects:{ini:"Currículo online semântico",mid:"Formulário de cadastro com validação nativa",sen:"Blog com SEO e nota 100 no Lighthouse"},
    q:"Por que usar nav e main em vez de div?", a:"Leitores de tela e buscadores entendem a estrutura da página." },
  { name:"UX e usabilidade na prática", kw:"Bootstrap, Estilização, Design responsivo, Media queries, Flex box, Responsividade",
    what:"Aplicar CSS responsivo com Flexbox, Grid, media queries e frameworks.",
    why:"A maior parte dos acessos vem do celular.",
    how:["Comece pelo layout mobile.","Use Flexbox e Grid.","Adicione media queries só onde o layout quebra."],
    tools:["CSS","Bootstrap","Tailwind","DevTools"],
    projects:{ini:"Landing page responsiva",mid:"Dashboard com Grid e Flexbox",sen:"Design system próprio com tokens e tema escuro"},
    q:"O que significa Mobile First?", a:"Projetar para telas pequenas primeiro e ampliar depois." },
  { name:"BOM e DOM", kw:"Interatividade, Memória e mutabilidade, Caching, Cookies, Gatilhos de ação, Box model, Framework",
    what:"DOM é a árvore da página. BOM dá acesso ao navegador: janela, histórico, armazenamento.",
    why:"É a base de qualquer interatividade, inclusive dentro de frameworks.",
    how:["Selecione elementos e escute eventos.","Guarde estado em localStorage.","Use fetch com cache simples."],
    tools:["JavaScript","DevTools","React","Vite"],
    projects:{ini:"Lista de tarefas com DOM",mid:"App de clima com fetch e cache",sen:"SPA com roteador próprio e Service Worker"},
    q:"Qual a diferença entre DOM e BOM?", a:"DOM representa o documento. BOM representa o navegador." },
  { name:"Acessibilidade eMAG e WCAG", kw:"Perceptível, operável, Compreensível e Robusto, Mobile First, Interface perfeita, CI/CD",
    what:"Normas para que todas as pessoas usem o site. A eMAG é o padrão do governo brasileiro.",
    why:"É direito, é lei no setor público e amplia o seu público.",
    how:["Navegue só com o teclado.","Cheque contraste e textos alternativos.","Automatize auditorias no CI."],
    tools:["axe DevTools","WAVE","NVDA","Lighthouse CI"],
    projects:{ini:"Corrigir contraste e foco de uma página",mid:"Formulário acessível com ARIA",sen:"Auditoria de site público com leitor de tela e CI"},
    q:"O que significa POUR no WCAG?", a:"Perceptível, operável, compreensível e robusto." }
]},
{ id:"ops", name:"Estrutura DevOps, hiperautomação e IoT", color:"#fbbf24",
  tip:"Código só gera valor quando chega ao usuário. Automatize tudo que você faz mais de duas vezes.",
  topics:[
  { name:"Pipeline DevOps e CI/CD", kw:"Requisitos, Arquitetura, Construção, Teste, Controle de versão, Deploy, Correção, Monitoramento",
    what:"Esteira automática que testa e publica o código a cada commit.",
    why:"Entregas rápidas, previsíveis e com menos erro humano.",
    how:["Versione com Git e branches.","Crie um workflow que roda os testes.","Publique automaticamente se passar."],
    tools:["Git","GitHub Actions","GitLab CI","Vercel"],
    projects:{ini:"Workflow que roda testes no GitHub Actions",mid:"Deploy automático no GitHub Pages",sen:"Pipeline multiestágio com aprovação e rollback"},
    q:"Qual a diferença entre entrega e implantação contínua?", a:"Na entrega, a publicação exige aprovação manual. Na implantação, é automática." },
  { name:"IaC e containers", kw:"Toolchain, Versionamento, CI/Automação, Compilação/Container, Chef, Puppet, Ansible, Kernel",
    what:"Infraestrutura descrita em código e aplicações empacotadas em containers.",
    why:"Resolve o clássico problema do funciona na minha máquina.",
    how:["Escreva um Dockerfile.","Use docker compose para app e banco.","Provisione servidores com Ansible."],
    tools:["Docker","Docker Compose","Ansible","Terraform"],
    projects:{ini:"Dockerfile para seu site",mid:"App e banco de dados com Compose",sen:"Provisionar uma VM com Terraform e Ansible"},
    q:"O que um container isola?", a:"Processos, dependências e sistema de arquivos, compartilhando o kernel do host." },
  { name:"Scripts, RPA e IA", kw:"Regras, APIs, Fluxo de trabalho, Assistente virtual, Machine Learning, Analytics, Big Data, Cloud Computing, Dashboards",
    what:"Automação de tarefas com scripts, robôs de processo (RPA), APIs e modelos de IA.",
    why:"Libera tempo para trabalho de maior valor.",
    how:["Liste tarefas repetitivas.","Automatize com script ou API.","Mostre os resultados em um dashboard."],
    tools:["Python","n8n","Power Automate","scikit-learn","Metabase"],
    projects:{ini:"Script que organiza arquivos por tipo",mid:"Robô que coleta dados e gera planilha",sen:"Pipeline com modelo de ML e dashboard"},
    q:"RPA e script: qual a diferença?", a:"RPA imita ações humanas na interface. Script chama código ou APIs diretamente." },
  { name:"Gestão de riscos e IoT", kw:"Teste de sistema, integração e unidade, Zona Breakdown, Matriz qualitativa/quantitativa, Sensores, Atuadores",
    what:"Identificar e tratar riscos e conectar sensores e atuadores a sistemas de software.",
    why:"Software que controla coisas físicas não pode falhar sem plano.",
    how:["Monte a matriz de probabilidade e impacto.","Escreva testes de unidade, integração e sistema.","Leia um sensor e envie via MQTT."],
    tools:["ESP32","Wokwi","Node-RED","MQTT","Planilha de riscos"],
    projects:{ini:"Matriz de riscos de um projeto de faculdade",mid:"Sensor de temperatura enviando dados ao celular",sen:"Plataforma IoT com MQTT, dashboard e alertas"},
    q:"Como se calcula a exposição ao risco?", a:"Probabilidade multiplicada pelo impacto." }
]}
];
